import os
PATH_IMAGE_FILE = ''
DATABASE_URI = 'test.db'
SQLALCHEMY_DATABASE_URI = 'sqlite:///{0}{1}'.format(PATH_IMAGE_FILE,DATABASE_URI)
SQLALCHEMY_TRACK_MODIFICATIONS = False
SESSION_TYPE = 'SESSION_MONGODB'
#SESSION_TYPE = 'filesystem'
SECRET_KEY = os.urandom(16)
DEBUG = True
HOST = '0.0.0.0'
PORT = 5000
